# Generated by Django 5.1.5 on 2025-01-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_review_cover_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
